# This is a single line comment
print("****LEARNING ESCAPE SEQUENCES*****")
print("The itsy bitsy spider\nclimbed up the wall.")
print()
print("Down came the rain \nand washed the spider out.")
print("*********")
print("****PASSING MULTIPLE ARGUMENTS TO THE PRINT() FUNCTION*****")
print("The itsy bitsy spider","climbed up the wall.")
print()
print("My name is","Ptyhon.")
print("Monty Python.")
""" This is a multi-line comment"""
print("******USING KEYWORD ARGUMENTS*******")
print("My name is ", end="")
print("Monty Python.")
print("*********")
print("My name is", "Python.", end="\n")
print("Monty Python.")
print("*********")
print("My", "name", "is", "Monty", "Python.", sep="-")
print("*********")
print("My", "name", "is", sep="_", end="*")
print("Monty", "Python.", sep="*", end="*\n")
